right:
  foot_grasping:
    fsr_deltaThreshold: 1000
    fsr_nbSamplesOffset: 200
    fsr_filterAlpha: 0.98
left:
  foot_grasping:
    fsr_deltaThreshold: 1000
    fsr_nbSamplesOffset: 200
    fsr_filterAlpha: 0.97
